sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NKZJW9Gf7A8wkXomwyNBeflQC6cTWcoh1P6Nin4UgmCfvG/OcX+Dr/aX5aTJKVjEfKiJtAqiz+e9nMLBLOnk8JZh4R4/rG/wmQsu/d3GJGNVtrmlH7SYWpaYNi0k9mhj0nFAu0RFTvPNfj6Xq702rWVr7/kFHr035eh9ijvV2mOdRFXt4XIVwOOhsK6afJxgrPY5a20cj9KQknstwPh1ons1HDs0WwrH928i3U4XfNot+lP7w9zA13LXW1SvpVfldxnvWd9khNGb352n2n/FCp3WVuQnFH/qLyWiJzd+j6AlQG7KWApjE++hpONHV2+W8uV4GDLE+wjE306rfVLKAc6S1deBuYXkVXo6aUmOYikF1s2zNX0H0DBSsB9uN6Nd2Eau5Ulxb3X0KknAXwek14XUwS0Uurz+xcf0C65ZSN+zV/9hMr2sdZ7QWpcj0vhEB4tZyj2V69IJZsxifl3lJcSEDNtK7C0FWcl3lvwPbYthfAZNw5V/Xkyuj7jJndhoPj9MJOkEzJfDdhhpqqPMTRllGs7qXqjNbiBRs9tvycGaGjDTKj6CB3mLHjHhqXJznLgoxMlgd9rcolirbZfasOAuRhYDGtXnUleVq1j3LlOa8OVxVJtEJ0xBqeHBluNBhntjPSrGPOTpXQua4siwIepZ7YTxpcNJCKxC8SNRU4c=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Ballad-of-the-White-Horse_1719
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy